;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hydra-multiple-cursors/nil
        indent-for-tab-command
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-forward-slurp-sexp
        sp-kill-word
        sp-splice-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        ))
