;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        mwim-end-of-code-or-line
        sp-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        ))
