;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/sort-regions-and-exit
        indent-for-tab-command
        mwim-beginning-of-code-or-line
        mwim-end-of-code-or-line
        sp-backward-delete-char
        sp-delete-char
        sp-forward-barf-sexp
        sp-forward-slurp-sexp
        sp-kill-word
        sp-remove-active-pair-overlay
        sp-rewrap-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/ignore
        hydra-multiple-cursors/mc/add-cursor-on-click
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/skip-to-previous-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/nil
        ))
